/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProfileId = IDL.Nat;
export const CompanySize = IDL.Variant({
  'smb' : IDL.Null,
  'enterprise' : IDL.Null,
  'startup' : IDL.Null,
  'midMarket' : IDL.Null,
});
export const BudgetRange = IDL.Variant({
  'lessThan10k' : IDL.Null,
  'fiftyKTo200k' : IDL.Null,
  'moreThan200k' : IDL.Null,
  'tenKTo50k' : IDL.Null,
});
export const CreateProfileInput = IDL.Record({
  'name' : IDL.Text,
  'useCase' : IDL.Text,
  'decisionMakers' : IDL.Vec(IDL.Text),
  'painPoints' : IDL.Vec(IDL.Text),
  'companySize' : IDL.Opt(CompanySize),
  'budgetRange' : IDL.Opt(BudgetRange),
  'targetGeography' : IDL.Text,
  'industry' : IDL.Text,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Profile = IDL.Record({
  'id' : ProfileId,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'useCase' : IDL.Text,
  'decisionMakers' : IDL.Vec(IDL.Text),
  'updatedAt' : Timestamp,
  'painPoints' : IDL.Vec(IDL.Text),
  'shareCode' : IDL.Opt(IDL.Text),
  'companySize' : IDL.Opt(CompanySize),
  'budgetRange' : IDL.Opt(BudgetRange),
  'targetGeography' : IDL.Text,
  'industry' : IDL.Text,
});
export const PublicProfile = IDL.Record({
  'id' : ProfileId,
  'name' : IDL.Text,
  'useCase' : IDL.Text,
  'decisionMakers' : IDL.Vec(IDL.Text),
  'painPoints' : IDL.Vec(IDL.Text),
  'companySize' : IDL.Opt(CompanySize),
  'budgetRange' : IDL.Opt(BudgetRange),
  'targetGeography' : IDL.Text,
  'industry' : IDL.Text,
});
export const UpdateProfileInput = IDL.Record({
  'id' : ProfileId,
  'name' : IDL.Opt(IDL.Text),
  'useCase' : IDL.Opt(IDL.Text),
  'decisionMakers' : IDL.Opt(IDL.Vec(IDL.Text)),
  'painPoints' : IDL.Opt(IDL.Vec(IDL.Text)),
  'companySize' : IDL.Opt(CompanySize),
  'budgetRange' : IDL.Opt(BudgetRange),
  'targetGeography' : IDL.Opt(IDL.Text),
  'industry' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'calculateCompleteness' : IDL.Func(
      [ProfileId],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'createProfile' : IDL.Func([CreateProfileInput], [Profile], []),
  'deleteProfile' : IDL.Func([ProfileId], [IDL.Bool], []),
  'generateShareCode' : IDL.Func([ProfileId], [IDL.Opt(IDL.Text)], []),
  'getProfile' : IDL.Func([ProfileId], [IDL.Opt(Profile)], ['query']),
  'getPublicProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicProfile)],
      ['query'],
    ),
  'getRefinementSuggestions' : IDL.Func(
      [ProfileId],
      [IDL.Opt(IDL.Vec(IDL.Text))],
      ['query'],
    ),
  'listProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'updateProfile' : IDL.Func([UpdateProfileInput], [IDL.Opt(Profile)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProfileId = IDL.Nat;
  const CompanySize = IDL.Variant({
    'smb' : IDL.Null,
    'enterprise' : IDL.Null,
    'startup' : IDL.Null,
    'midMarket' : IDL.Null,
  });
  const BudgetRange = IDL.Variant({
    'lessThan10k' : IDL.Null,
    'fiftyKTo200k' : IDL.Null,
    'moreThan200k' : IDL.Null,
    'tenKTo50k' : IDL.Null,
  });
  const CreateProfileInput = IDL.Record({
    'name' : IDL.Text,
    'useCase' : IDL.Text,
    'decisionMakers' : IDL.Vec(IDL.Text),
    'painPoints' : IDL.Vec(IDL.Text),
    'companySize' : IDL.Opt(CompanySize),
    'budgetRange' : IDL.Opt(BudgetRange),
    'targetGeography' : IDL.Text,
    'industry' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Profile = IDL.Record({
    'id' : ProfileId,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'useCase' : IDL.Text,
    'decisionMakers' : IDL.Vec(IDL.Text),
    'updatedAt' : Timestamp,
    'painPoints' : IDL.Vec(IDL.Text),
    'shareCode' : IDL.Opt(IDL.Text),
    'companySize' : IDL.Opt(CompanySize),
    'budgetRange' : IDL.Opt(BudgetRange),
    'targetGeography' : IDL.Text,
    'industry' : IDL.Text,
  });
  const PublicProfile = IDL.Record({
    'id' : ProfileId,
    'name' : IDL.Text,
    'useCase' : IDL.Text,
    'decisionMakers' : IDL.Vec(IDL.Text),
    'painPoints' : IDL.Vec(IDL.Text),
    'companySize' : IDL.Opt(CompanySize),
    'budgetRange' : IDL.Opt(BudgetRange),
    'targetGeography' : IDL.Text,
    'industry' : IDL.Text,
  });
  const UpdateProfileInput = IDL.Record({
    'id' : ProfileId,
    'name' : IDL.Opt(IDL.Text),
    'useCase' : IDL.Opt(IDL.Text),
    'decisionMakers' : IDL.Opt(IDL.Vec(IDL.Text)),
    'painPoints' : IDL.Opt(IDL.Vec(IDL.Text)),
    'companySize' : IDL.Opt(CompanySize),
    'budgetRange' : IDL.Opt(BudgetRange),
    'targetGeography' : IDL.Opt(IDL.Text),
    'industry' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'calculateCompleteness' : IDL.Func(
        [ProfileId],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'createProfile' : IDL.Func([CreateProfileInput], [Profile], []),
    'deleteProfile' : IDL.Func([ProfileId], [IDL.Bool], []),
    'generateShareCode' : IDL.Func([ProfileId], [IDL.Opt(IDL.Text)], []),
    'getProfile' : IDL.Func([ProfileId], [IDL.Opt(Profile)], ['query']),
    'getPublicProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicProfile)],
        ['query'],
      ),
    'getRefinementSuggestions' : IDL.Func(
        [ProfileId],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
    'listProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'updateProfile' : IDL.Func([UpdateProfileInput], [IDL.Opt(Profile)], []),
  });
};

export const init = ({ IDL }) => { return []; };