/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BudgetRange = { 'lessThan10k' : null } |
  { 'fiftyKTo200k' : null } |
  { 'moreThan200k' : null } |
  { 'tenKTo50k' : null };
export type CompanySize = { 'smb' : null } |
  { 'enterprise' : null } |
  { 'startup' : null } |
  { 'midMarket' : null };
export interface CreateProfileInput {
  'name' : string,
  'useCase' : string,
  'decisionMakers' : Array<string>,
  'painPoints' : Array<string>,
  'companySize' : [] | [CompanySize],
  'budgetRange' : [] | [BudgetRange],
  'targetGeography' : string,
  'industry' : string,
}
export interface Profile {
  'id' : ProfileId,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'useCase' : string,
  'decisionMakers' : Array<string>,
  'updatedAt' : Timestamp,
  'painPoints' : Array<string>,
  'shareCode' : [] | [string],
  'companySize' : [] | [CompanySize],
  'budgetRange' : [] | [BudgetRange],
  'targetGeography' : string,
  'industry' : string,
}
export type ProfileId = bigint;
export interface PublicProfile {
  'id' : ProfileId,
  'name' : string,
  'useCase' : string,
  'decisionMakers' : Array<string>,
  'painPoints' : Array<string>,
  'companySize' : [] | [CompanySize],
  'budgetRange' : [] | [BudgetRange],
  'targetGeography' : string,
  'industry' : string,
}
export type Timestamp = bigint;
export interface UpdateProfileInput {
  'id' : ProfileId,
  'name' : [] | [string],
  'useCase' : [] | [string],
  'decisionMakers' : [] | [Array<string>],
  'painPoints' : [] | [Array<string>],
  'companySize' : [] | [CompanySize],
  'budgetRange' : [] | [BudgetRange],
  'targetGeography' : [] | [string],
  'industry' : [] | [string],
}
export type UserId = Principal;
export interface _SERVICE {
  'calculateCompleteness' : ActorMethod<[ProfileId], [] | [bigint]>,
  'createProfile' : ActorMethod<[CreateProfileInput], Profile>,
  'deleteProfile' : ActorMethod<[ProfileId], boolean>,
  'generateShareCode' : ActorMethod<[ProfileId], [] | [string]>,
  'getProfile' : ActorMethod<[ProfileId], [] | [Profile]>,
  'getPublicProfile' : ActorMethod<[string], [] | [PublicProfile]>,
  'getRefinementSuggestions' : ActorMethod<[ProfileId], [] | [Array<string>]>,
  'listProfiles' : ActorMethod<[], Array<Profile>>,
  'updateProfile' : ActorMethod<[UpdateProfileInput], [] | [Profile]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];