/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface PublicProfile {
    id: ProfileId;
    name: string;
    useCase: string;
    decisionMakers: Array<string>;
    painPoints: Array<string>;
    companySize?: CompanySize;
    budgetRange?: BudgetRange;
    targetGeography: string;
    industry: string;
}
export interface UpdateProfileInput {
    id: ProfileId;
    name?: string;
    useCase?: string;
    decisionMakers?: Array<string>;
    painPoints?: Array<string>;
    companySize?: CompanySize;
    budgetRange?: BudgetRange;
    targetGeography?: string;
    industry?: string;
}
export interface CreateProfileInput {
    name: string;
    useCase: string;
    decisionMakers: Array<string>;
    painPoints: Array<string>;
    companySize?: CompanySize;
    budgetRange?: BudgetRange;
    targetGeography: string;
    industry: string;
}
export type ProfileId = bigint;
export interface Profile {
    id: ProfileId;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    useCase: string;
    decisionMakers: Array<string>;
    updatedAt: Timestamp;
    painPoints: Array<string>;
    shareCode?: string;
    companySize?: CompanySize;
    budgetRange?: BudgetRange;
    targetGeography: string;
    industry: string;
}
export enum BudgetRange {
    lessThan10k = "lessThan10k",
    fiftyKTo200k = "fiftyKTo200k",
    moreThan200k = "moreThan200k",
    tenKTo50k = "tenKTo50k"
}
export enum CompanySize {
    smb = "smb",
    enterprise = "enterprise",
    startup = "startup",
    midMarket = "midMarket"
}
export interface backendInterface {
    calculateCompleteness(id: ProfileId): Promise<bigint | null>;
    createProfile(input: CreateProfileInput): Promise<Profile>;
    deleteProfile(id: ProfileId): Promise<boolean>;
    generateShareCode(id: ProfileId): Promise<string | null>;
    getProfile(id: ProfileId): Promise<Profile | null>;
    getPublicProfile(shareCode: string): Promise<PublicProfile | null>;
    getRefinementSuggestions(id: ProfileId): Promise<Array<string> | null>;
    listProfiles(): Promise<Array<Profile>>;
    updateProfile(input: UpdateProfileInput): Promise<Profile | null>;
}
import type { BudgetRange as _BudgetRange, CompanySize as _CompanySize, CreateProfileInput as _CreateProfileInput, Profile as _Profile, ProfileId as _ProfileId, PublicProfile as _PublicProfile, Timestamp as _Timestamp, UpdateProfileInput as _UpdateProfileInput, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateCompleteness(arg0: ProfileId): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateCompleteness(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateCompleteness(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProfile(arg0: CreateProfileInput): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(to_candid_CreateProfileInput_n2(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Profile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(to_candid_CreateProfileInput_n2(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Profile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProfile(arg0: ProfileId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProfile(arg0);
            return result;
        }
    }
    async generateShareCode(arg0: ProfileId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.generateShareCode(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateShareCode(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: ProfileId): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicProfile(arg0: string): Promise<PublicProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRefinementSuggestions(arg0: ProfileId): Promise<Array<string> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRefinementSuggestions(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRefinementSuggestions(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProfiles(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProfiles();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProfiles();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: UpdateProfileInput): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_UpdateProfileInput_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_UpdateProfileInput_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BudgetRange_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetRange): BudgetRange {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CompanySize_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanySize): CompanySize {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PublicProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicProfile): PublicProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanySize]): CompanySize | null {
    return value.length === 0 ? null : from_candid_CompanySize_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BudgetRange]): BudgetRange | null {
    return value.length === 0 ? null : from_candid_BudgetRange_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicProfile]): PublicProfile | null {
    return value.length === 0 ? null : from_candid_PublicProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProfileId;
    name: string;
    useCase: string;
    decisionMakers: Array<string>;
    painPoints: Array<string>;
    companySize: [] | [_CompanySize];
    budgetRange: [] | [_BudgetRange];
    targetGeography: string;
    industry: string;
}): {
    id: ProfileId;
    name: string;
    useCase: string;
    decisionMakers: Array<string>;
    painPoints: Array<string>;
    companySize?: CompanySize;
    budgetRange?: BudgetRange;
    targetGeography: string;
    industry: string;
} {
    return {
        id: value.id,
        name: value.name,
        useCase: value.useCase,
        decisionMakers: value.decisionMakers,
        painPoints: value.painPoints,
        companySize: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.companySize)),
        budgetRange: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.budgetRange)),
        targetGeography: value.targetGeography,
        industry: value.industry
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProfileId;
    owner: _UserId;
    name: string;
    createdAt: _Timestamp;
    useCase: string;
    decisionMakers: Array<string>;
    updatedAt: _Timestamp;
    painPoints: Array<string>;
    shareCode: [] | [string];
    companySize: [] | [_CompanySize];
    budgetRange: [] | [_BudgetRange];
    targetGeography: string;
    industry: string;
}): {
    id: ProfileId;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    useCase: string;
    decisionMakers: Array<string>;
    updatedAt: Timestamp;
    painPoints: Array<string>;
    shareCode?: string;
    companySize?: CompanySize;
    budgetRange?: BudgetRange;
    targetGeography: string;
    industry: string;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        useCase: value.useCase,
        decisionMakers: value.decisionMakers,
        updatedAt: value.updatedAt,
        painPoints: value.painPoints,
        shareCode: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.shareCode)),
        companySize: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.companySize)),
        budgetRange: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.budgetRange)),
        targetGeography: value.targetGeography,
        industry: value.industry
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    smb: null;
} | {
    enterprise: null;
} | {
    startup: null;
} | {
    midMarket: null;
}): CompanySize {
    return "smb" in value ? CompanySize.smb : "enterprise" in value ? CompanySize.enterprise : "startup" in value ? CompanySize.startup : "midMarket" in value ? CompanySize.midMarket : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lessThan10k: null;
} | {
    fiftyKTo200k: null;
} | {
    moreThan200k: null;
} | {
    tenKTo50k: null;
}): BudgetRange {
    return "lessThan10k" in value ? BudgetRange.lessThan10k : "fiftyKTo200k" in value ? BudgetRange.fiftyKTo200k : "moreThan200k" in value ? BudgetRange.moreThan200k : "tenKTo50k" in value ? BudgetRange.tenKTo50k : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n8(_uploadFile, _downloadFile, x));
}
function to_candid_BudgetRange_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetRange): _BudgetRange {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_CompanySize_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompanySize): _CompanySize {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProfileInput_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProfileInput): _CreateProfileInput {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileInput): _UpdateProfileInput {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProfileId;
    name?: string;
    useCase?: string;
    decisionMakers?: Array<string>;
    painPoints?: Array<string>;
    companySize?: CompanySize;
    budgetRange?: BudgetRange;
    targetGeography?: string;
    industry?: string;
}): {
    id: _ProfileId;
    name: [] | [string];
    useCase: [] | [string];
    decisionMakers: [] | [Array<string>];
    painPoints: [] | [Array<string>];
    companySize: [] | [_CompanySize];
    budgetRange: [] | [_BudgetRange];
    targetGeography: [] | [string];
    industry: [] | [string];
} {
    return {
        id: value.id,
        name: value.name ? candid_some(value.name) : candid_none(),
        useCase: value.useCase ? candid_some(value.useCase) : candid_none(),
        decisionMakers: value.decisionMakers ? candid_some(value.decisionMakers) : candid_none(),
        painPoints: value.painPoints ? candid_some(value.painPoints) : candid_none(),
        companySize: value.companySize ? candid_some(to_candid_CompanySize_n4(_uploadFile, _downloadFile, value.companySize)) : candid_none(),
        budgetRange: value.budgetRange ? candid_some(to_candid_BudgetRange_n6(_uploadFile, _downloadFile, value.budgetRange)) : candid_none(),
        targetGeography: value.targetGeography ? candid_some(value.targetGeography) : candid_none(),
        industry: value.industry ? candid_some(value.industry) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    useCase: string;
    decisionMakers: Array<string>;
    painPoints: Array<string>;
    companySize?: CompanySize;
    budgetRange?: BudgetRange;
    targetGeography: string;
    industry: string;
}): {
    name: string;
    useCase: string;
    decisionMakers: Array<string>;
    painPoints: Array<string>;
    companySize: [] | [_CompanySize];
    budgetRange: [] | [_BudgetRange];
    targetGeography: string;
    industry: string;
} {
    return {
        name: value.name,
        useCase: value.useCase,
        decisionMakers: value.decisionMakers,
        painPoints: value.painPoints,
        companySize: value.companySize ? candid_some(to_candid_CompanySize_n4(_uploadFile, _downloadFile, value.companySize)) : candid_none(),
        budgetRange: value.budgetRange ? candid_some(to_candid_BudgetRange_n6(_uploadFile, _downloadFile, value.budgetRange)) : candid_none(),
        targetGeography: value.targetGeography,
        industry: value.industry
    };
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompanySize): {
    smb: null;
} | {
    enterprise: null;
} | {
    startup: null;
} | {
    midMarket: null;
} {
    return value == CompanySize.smb ? {
        smb: null
    } : value == CompanySize.enterprise ? {
        enterprise: null
    } : value == CompanySize.startup ? {
        startup: null
    } : value == CompanySize.midMarket ? {
        midMarket: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetRange): {
    lessThan10k: null;
} | {
    fiftyKTo200k: null;
} | {
    moreThan200k: null;
} | {
    tenKTo50k: null;
} {
    return value == BudgetRange.lessThan10k ? {
        lessThan10k: null
    } : value == BudgetRange.fiftyKTo200k ? {
        fiftyKTo200k: null
    } : value == BudgetRange.moreThan200k ? {
        moreThan200k: null
    } : value == BudgetRange.tenKTo50k ? {
        tenKTo50k: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
